services:
  traefik:
    profiles:
      - self-proxy
    image: traefik:v3.6
    container_name: ${PROJECT_NAME:-nero}-traefik
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"
    command:
      - --global.sendanonymoususage=false
      - --api.dashboard=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=${NERO_EDGE_NETWORK:-nero-edge}
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.cloudflare.acme.storage=/var/traefik/acme.json
      - --log.level=INFO
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik:/var/traefik
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
    networks:
      - edge

networks:
  # Created by `nero install` (docker network create); shared with other stacks / Traefik.
  edge:
    external: true
    name: ${NERO_EDGE_NETWORK:-nero-edge}
